"""change table user

Revision ID: a7de10cb11bb
Revises: 49cafe92495b
Create Date: 2024-04-18 10:44:45.382384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7de10cb11bb'
down_revision: Union[str, None] = '49cafe92495b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    op.drop_column('users', 'story')
    op.drop_column('users', 'cosplay')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cosplay', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('story', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('picture', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
